language: python
python:
  - "3.4"
  install:
  - pip install flake8 autopep8
  script:
  - cd ./ecommers
  - flake8 --max-line-length=160 --exclude ./compras/migrations ./compras
  - python3 manage.py test test_entities.py
