language: python
python:
 - "3.5"
install:
 - sudo apt-get install python3-setuptools
 - sudo easy_install3 pip
 - pip3 install 'django<1.9'
 - pip3 install flake8
 - pip3 install autopep8
script:
 - ls -l
 - cd ./ecommerce
 - ls -l
 - cd compras
 - ls -l
 - autopep8 entities.py --in-place
 - autopep8 tests/tests_entities.py -- in-place
 - rm -r migrations
 - ls -l
 - cd ..
 - ls -l
 - python3 manage.py makemigrations compras
 - python3 manage.py migrate
 - python3 manage.py test compras
 
 - flake8 --max-line-length=160 --exclude ./compras/migrations ./compras


